name: Meela Leino
favicon: null
layout_spectrum: 0.08521302975714207
typography_spectrum: 0.037541241850703955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9304422864224762
  lightness: 0.8525086217559874
  saturation: 0.14806238422170281
  rhythmicContrast: 0.6655479604378343
purpose: []
